const ACTIONS = {
    LOGIN: 'LOGIN',
    RELOAD: 'RELOAD',
    LOGOUT: 'LOGOUT',
    FETCH: 'FETCH',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    REGISTER: 'REGISTER',
    GETUSER: 'GETUSER',
    SEARCHROOM: 'SEARCHROOM',
    SEARCHSUCCESS: 'SEARCHSUCCESS',
    SEARCHFAILED: 'SEARCHFAILED',
    FETCH_MENU: 'MENUFETCH',
    SUCCESS_MENU: 'MENUSUCCESS',
    FAILED_MENU: 'MENUFAILED',
};
export default ACTIONS;
